# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Archive unity build"
  lane :archive_unity_build do
    sh "xcodebuild archive \
        -project ../build/Unity-iPhone.xcodeproj \
        -scheme UnityFramework \
        -destination \"generic/platform=iOS\" \
        -archivePath \"../build/ios\" \
        SKIP_INSTALL=NO \
        BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
  end

  desc "Create unity xcframework (contains both simulator and unity), it need simulator and unity archive"
  lane :create_xcframework do
    buildDir = "../build"
    unityBuildDir = "#{buildDir}"

    if Dir.exist?("#{unityBuildDir}/Unity.xcframework")
      sh "rm -rf #{unityBuildDir}/Unity.xcframework"
    end
    
    sh "xcodebuild -create-xcframework \
      -framework #{unityBuildDir}/ios.xcarchive/Products/Library/Frameworks/UnityFramework.framework \
      -debug-symbols #{File.expand_path("#{unityBuildDir}/ios.xcarchive/dSYMs/UnityFramework.framework.dSYM")} \
      -output #{unityBuildDir}/Unity.xcframework"
  end
end